version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm i
      - run:
          name: Run Tests
          command: npm run dev

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          ssh: true
